{
    "createtime": 1606119043000,
        "menuList": [
            {
                "menuPerms": "",
                "menuStatus": 0,
                "menuVisible": 0,
                "menuIconStr": "home",
                "menuPid": 0,
                "menuName": "首页",
                "updateTime": "2020-12-24T09:12:36",
                "menuRemark": "",
                "menuModal": "/index",
                "createTime": "2020-11-18T14:11:40",
                "menuUrlType": 1,
                "childMenus": [],
                "menuId": 779,
                "menuType": "M",
                "menuSort": 1
            },
            {
                "menuPerms": "",
                "menuStatus": 0,
                "menuVisible": 0,
                "menuIconStr": "goods",
                "menuPid": 0,
                "menuName": "商品管理",
                "updateTime": "2024-08-31T10:29:34",
                "menuRemark": "",
                "menuModal": "/poduct/manage",
                "createTime": "2020-11-18T14:53:12",
                "menuUrlType": 1,
                "childMenus": [
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 806,
                        "menuName": "本店商品",
                        "updateTime": "2020-11-18T14:56:25",
                        "menuRemark": "",
                        "menuModal": "/item",
                        "createTime": "2020-11-18T14:56:25",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 810,
                                "menuName": "商品上架",
                                "updateTime": "2023-11-07T15:18:09",
                                "menuRemark": "",
                                "menuModal": "/storeManage/commodityManage/productList/index",
                                "createTime": "2020-11-18T14:57:04",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 811,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 810,
                                "menuName": "商品管理",
                                "updateTime": "2020-11-18T15:16:26",
                                "menuRemark": "",
                                "menuModal": "/storeManage/commodityManage/giftsList",
                                "createTime": "2020-11-18T14:58:30",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 812,
                                "menuType": "M",
                                "menuSort": 0
                            }
                        ],
                        "menuId": 810,
                        "menuType": "M",
                        "menuSort": 0
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 806,
                        "menuName": "连锁化商品",
                        "updateTime": "2020-11-18T14:53:40",
                        "menuRemark": "",
                        "menuModal": "/chain/product",
                        "createTime": "2020-11-18T14:53:40",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 807,
                                "menuName": "连锁化商品上架",
                                "updateTime": "2020-11-18T14:54:27",
                                "menuRemark": "",
                                "menuModal": "/storeManage/chainGoods/productList",
                                "createTime": "2020-11-18T14:54:27",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 808,
                                "menuType": "M",
                                "menuSort": 1
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 807,
                                "menuName": "连锁化商品管理",
                                "updateTime": "2020-11-18T14:55:18",
                                "menuRemark": "",
                                "menuModal": "/storeManage/chainGoods/giftsList",
                                "createTime": "2020-11-18T14:55:18",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 809,
                                "menuType": "M",
                                "menuSort": 2
                            }
                        ],
                        "menuId": 807,
                        "menuType": "M",
                        "menuSort": 1
                    }
                ],
                "menuId": 806,
                "menuType": "M",
                "menuSort": 11
            },
            {
                "menuPerms": "",
                "menuStatus": 0,
                "menuVisible": 0,
                "menuIconStr": "marketing",
                "menuPid": 0,
                "menuName": "我的活动",
                "updateTime": "2024-08-31T10:26:55",
                "menuRemark": "",
                "menuModal": "/",
                "createTime": "2020-11-18T14:45:16",
                "menuUrlType": 1,
                "childMenus": [
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 796,
                        "menuName": "Banner审核",
                        "updateTime": "2021-05-27T09:51:51",
                        "menuRemark": "",
                        "menuModal": "/bannerManage/bannerAudit",
                        "createTime": "2021-05-27T09:51:51",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 1364,
                        "menuType": "M",
                        "menuSort": 0
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 796,
                        "menuName": "Banner管理",
                        "updateTime": "2020-11-18T16:21:31",
                        "menuRemark": "",
                        "menuModal": "/bannerManage/bannerManage",
                        "createTime": "2020-11-18T14:46:00",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 797,
                        "menuType": "M",
                        "menuSort": 1
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 796,
                        "menuName": "靓号管理",
                        "updateTime": "2020-11-24T15:36:37",
                        "menuRemark": "",
                        "menuModal": "/numberManage",
                        "createTime": "2020-11-18T14:47:59",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 801,
                                "menuName": "靓号管理",
                                "updateTime": "2020-11-24T15:38:55",
                                "menuRemark": "",
                                "menuModal": "/numberManage/numberManage",
                                "createTime": "2020-11-24T15:36:03",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 846,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 801,
                                "menuName": "靓号等级管理",
                                "updateTime": "2020-11-24T15:38:01",
                                "menuRemark": "",
                                "menuModal": "/numberManage/numberLevel",
                                "createTime": "2020-11-24T15:36:25",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 847,
                                "menuType": "M",
                                "menuSort": 0
                            }
                        ],
                        "menuId": 801,
                        "menuType": "M",
                        "menuSort": 3
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 796,
                        "menuName": "专题管理",
                        "updateTime": "2020-11-18T16:23:44",
                        "menuRemark": "",
                        "menuModal": "/thematicPage",
                        "createTime": "2020-11-18T14:47:04",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 799,
                                "menuName": "专题页类型",
                                "updateTime": "2020-11-18T16:22:58",
                                "menuRemark": "",
                                "menuModal": "/thematicPage/pageType",
                                "createTime": "2020-11-18T16:22:58",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 834,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 799,
                                "menuName": "专题页详情",
                                "updateTime": "2020-11-18T16:23:18",
                                "menuRemark": "",
                                "menuModal": "/thematicPage/pageDetail",
                                "createTime": "2020-11-18T16:23:18",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 835,
                                "menuType": "M",
                                "menuSort": 0
                            }
                        ],
                        "menuId": 799,
                        "menuType": "M",
                        "menuSort": 4
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 796,
                        "menuName": "积分活动管理",
                        "updateTime": "2023-12-25T18:43:44",
                        "menuRemark": "",
                        "menuModal": "/coins",
                        "createTime": "2020-11-18T15:32:42",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 825,
                                "menuName": "抽奖配置",
                                "updateTime": "2020-11-18T15:33:17",
                                "menuRemark": "",
                                "menuModal": "/prize/prize",
                                "createTime": "2020-11-18T15:33:17",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 826,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 825,
                                "menuName": "抽奖记录管理",
                                "updateTime": "2020-11-18T15:33:33",
                                "menuRemark": "",
                                "menuModal": "/lotteryRecord/lotteryRecord",
                                "createTime": "2020-11-18T15:33:33",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 827,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 825,
                                "menuName": "兑换商品管理",
                                "updateTime": "2020-11-18T15:33:51",
                                "menuRemark": "",
                                "menuModal": "/exchangeGoods/exchangeGoods",
                                "createTime": "2020-11-18T15:33:51",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 828,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 825,
                                "menuName": "兑换记录管理",
                                "updateTime": "2020-11-18T15:34:15",
                                "menuRemark": "",
                                "menuModal": "/exchangeRecord/exchangeRecord",
                                "createTime": "2020-11-18T15:34:15",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 829,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 825,
                                "menuName": "签到管理",
                                "updateTime": "2020-11-18T15:34:32",
                                "menuRemark": "",
                                "menuModal": "/sign/sign",
                                "createTime": "2020-11-18T15:34:32",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 830,
                                "menuType": "M",
                                "menuSort": 0
                            }
                        ],
                        "menuId": 825,
                        "menuType": "M",
                        "menuSort": 5
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuIconStr": "",
                        "menuPid": 796,
                        "menuName": "宣传海报",
                        "updateTime": "2022-11-01T09:52:00",
                        "menuRemark": "",
                        "menuModal": "/kehuaDesign",
                        "createTime": "2021-07-16T18:27:39",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1424,
                                "menuName": "宣传海报设计",
                                "updateTime": "2021-07-16T18:28:53",
                                "menuRemark": "",
                                "menuModal": "/canva/canva/index",
                                "createTime": "2021-03-04T14:22:41",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1009,
                                "menuType": "M",
                                "menuSort": 31
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1424,
                                "menuName": "宣传设计海报审核",
                                "updateTime": "2021-07-16T18:29:13",
                                "menuRemark": "",
                                "menuModal": "/canva/canvaAudit/index",
                                "createTime": "2021-07-12T16:47:18",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1414,
                                "menuType": "C",
                                "menuSort": 31
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1424,
                                "menuName": "素材库",
                                "updateTime": "2021-09-23T11:12:11",
                                "menuRemark": "",
                                "menuModal": "/canva/canvaPassList/index",
                                "createTime": "2021-09-23T11:12:11",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1454,
                                "menuType": "M",
                                "menuSort": 32
                            }
                        ],
                        "menuId": 1424,
                        "menuType": "M",
                        "menuSort": 13
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 796,
                        "menuName": "优惠券管理",
                        "updateTime": "2022-11-01T09:40:29",
                        "menuRemark": "",
                        "menuModal": "/coupons/coupons/index",
                        "createTime": "2021-01-08T11:16:09",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 907,
                        "menuType": "M",
                        "menuSort": 21
                    }
                ],
                "menuId": 796,
                "menuType": "M",
                "menuSort": 6
            },
            {
                "menuPerms": "",
                "menuStatus": 0,
                "menuVisible": 0,
                "menuIconStr": "orders",
                "menuPid": 0,
                "menuName": "我的订单",
                "updateTime": "2024-08-31T10:26:45",
                "menuRemark": "",
                "menuModal": "/orders/orders",
                "createTime": "2020-11-18T14:39:38",
                "menuUrlType": 1,
                "childMenus": [
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuIconStr": "",
                        "menuPid": 792,
                        "menuName": "订单查询",
                        "updateTime": "2022-11-01T09:57:53",
                        "menuRemark": "",
                        "menuModal": "/orders/orders",
                        "createTime": "2022-11-01T09:36:30",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 1581,
                        "menuType": "C",
                        "menuSort": 1
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuIconStr": "",
                        "menuPid": 792,
                        "menuName": "用户预约订单",
                        "updateTime": "2022-11-01T09:51:45",
                        "menuRemark": "",
                        "menuModal": "/bookingOrder/bookingOrder/index",
                        "createTime": "2021-01-15T10:49:59",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 931,
                        "menuType": "C",
                        "menuSort": 26
                    }
                ],
                "menuId": 792,
                "menuType": "M",
                "menuSort": 5
            },

            {
                "menuPerms": "",
                "menuStatus": 0,
                "menuVisible": 0,
                "menuIconStr": "user",
                "menuPid": 0,
                "menuName": "我的客户",
                "updateTime": "2024-08-31T10:26:37",
                "menuRemark": "",
                "menuModal": "/user",
                "createTime": "2020-11-18T14:41:34",
                "menuUrlType": 1,
                "childMenus": [
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 793,
                        "menuName": "用户管理",
                        "updateTime": "2024-09-02T15:15:59",
                        "menuRemark": "",
                        "menuModal": "/memberManage",
                        "createTime": "2020-11-18T14:42:20",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 794,
                                "menuName": "用户列表",
                                "updateTime": "2024-09-02T20:06:50",
                                "menuRemark": "",
                                "menuModal": "/memberManage/memberList",
                                "createTime": "2020-11-19T11:20:41",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 839,
                                "menuType": "M",
                                "menuSort": 1
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 794,
                                "menuName": "用户等级",
                                "updateTime": "2024-09-02T20:07:02",
                                "menuRemark": "",
                                "menuModal": "/memberManage/memberLevel",
                                "createTime": "2020-11-19T11:21:38",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 841,
                                "menuType": "M",
                                "menuSort": 3
                            }
                        ],
                        "menuId": 794,
                        "menuType": "M",
                        "menuSort": 1
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 793,
                        "menuName": "积分管理",
                        "updateTime": "2024-09-02T15:16:38",
                        "menuRemark": "",
                        "menuModal": "/integrationMenberMange",
                        "createTime": "2023-11-23T15:54:36",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2002,
                                "menuName": "会员列表",
                                "updateTime": "2023-11-27T15:29:09",
                                "menuRemark": "",
                                "menuModal": "/integrationMenberMange/memberList",
                                "createTime": "2023-11-23T15:56:08",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2003,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2002,
                                "menuName": "会员积分管理",
                                "updateTime": "2023-11-27T15:33:16",
                                "menuRemark": "",
                                "menuModal": "/integrationMenberMange/memberIntegral",
                                "createTime": "2023-11-27T15:33:16",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2015,
                                "menuType": "M",
                                "menuSort": 1
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2002,
                                "menuName": "会员等级",
                                "updateTime": "2023-11-27T15:40:38",
                                "menuRemark": "",
                                "menuModal": "/integrationMenberMange/memberLevel",
                                "createTime": "2023-11-23T16:24:35",
                                "menuUrl": "",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2004,
                                "menuType": "M",
                                "menuSort": 2
                            }
                        ],
                        "menuId": 2002,
                        "menuType": "M",
                        "menuSort": 2
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuIconStr": "",
                        "menuPid": 793,
                        "menuName": "签到规则",
                        "updateTime": "2024-09-02T15:16:36",
                        "menuRemark": "",
                        "menuModal": "/awardmanage",
                        "createTime": "2024-08-31T09:11:24",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2082,
                                "menuName": "积分管理规则",
                                "updateTime": "2024-08-31T09:13:35",
                                "menuRemark": "",
                                "menuModal": "/awardmanage/point",
                                "createTime": "2024-08-31T09:13:07",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2083,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2082,
                                "menuName": "积分明细列表",
                                "updateTime": "2024-08-31T09:28:04",
                                "menuRemark": "",
                                "menuModal": "/awardmanage/detail",
                                "createTime": "2024-08-31T09:14:05",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2084,
                                "menuType": "M",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2082,
                                "menuName": "积分签到列表",
                                "updateTime": "2024-09-01T17:02:39",
                                "menuRemark": "",
                                "menuModal": "/awardmanage/sign",
                                "createTime": "2024-09-01T17:02:39",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2093,
                                "menuType": "M",
                                "menuSort": 0
                            }
                        ],
                        "menuId": 2082,
                        "menuType": "M",
                        "menuSort": 3
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuIconStr": "",
                        "menuPid": 793,
                        "menuName": "标签管理",
                        "updateTime": "2024-09-02T15:16:26",
                        "menuRemark": "",
                        "menuModal": "/userTag",
                        "createTime": "2024-08-29T14:49:43",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2064,
                                "menuName": "标签管理",
                                "updateTime": "2024-08-30T19:36:20",
                                "menuRemark": "",
                                "menuModal": "/userTag/userTag",
                                "createTime": "2024-08-30T19:36:20",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2080,
                                "menuType": "M",
                                "menuSort": 1
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2064,
                                "menuName": "标签配置",
                                "updateTime": "2024-09-05T17:36:45",
                                "menuRemark": "",
                                "menuModal": "/userTag/tagRule",
                                "createTime": "2024-08-29T16:23:51",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2067,
                                "menuType": "M",
                                "menuSort": 2
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 2064,
                                "menuName": "规则条件配置",
                                "updateTime": "2024-09-05T17:36:47",
                                "menuRemark": "",
                                "menuModal": "/userTag/tagAttribute",
                                "createTime": "2024-08-29T16:24:24",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 2068,
                                "menuType": "M",
                                "menuSort": 3
                            }
                        ],
                        "menuId": 2064,
                        "menuType": "M",
                        "menuSort": 4
                    }
                ],
                "menuId": 793,
                "menuType": "M",
                "menuSort": 3
            },
            {
                "menuPerms": "",
                "menuStatus": 0,
                "menuVisible": 0,
                "menuIconStr": "products",
                "menuPid": 0,
                "menuName": "商户中心",
                "updateTime": "2024-08-31T10:26:43",
                "menuRemark": "",
                "menuModal": "/productManage",
                "createTime": "2020-11-18T14:30:13",
                "menuUrlType": 1,
                "childMenus": [
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 787,
                        "menuName": "产品管理",
                        "updateTime": "2020-12-11T14:30:28",
                        "menuRemark": "",
                        "menuModal": "/productManage/productManage",
                        "createTime": "2020-11-18T15:35:48",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 831,
                        "menuType": "M",
                        "menuSort": 0
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 787,
                        "menuName": "产品审核",
                        "updateTime": "2021-05-26T16:27:55",
                        "menuRemark": "",
                        "menuModal": "/productManage/productExamine",
                        "createTime": "2021-05-26T16:27:55",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 1360,
                        "menuType": "C",
                        "menuSort": 0
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 787,
                        "menuName": "品牌管理",
                        "updateTime": "2020-11-18T14:32:31",
                        "menuRemark": "",
                        "menuModal": "/productManage/brandManage",
                        "createTime": "2020-11-18T14:32:31",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 788,
                        "menuType": "M",
                        "menuSort": 1
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 787,
                        "menuName": "扩展参数管理",
                        "updateTime": "2020-11-18T14:33:01",
                        "menuRemark": "",
                        "menuModal": "/parameterManage/extendedParameter",
                        "createTime": "2020-11-18T14:33:01",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 789,
                        "menuType": "M",
                        "menuSort": 2
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 787,
                        "menuName": "分类管理",
                        "updateTime": "2020-11-18T15:08:45",
                        "menuRemark": "",
                        "menuModal": "/productManage/categoryManage",
                        "createTime": "2020-11-18T14:36:25",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 790,
                        "menuType": "M",
                        "menuSort": 3
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 787,
                        "menuName": "标签管理",
                        "updateTime": "2020-11-18T15:09:19",
                        "menuRemark": "",
                        "menuModal": "/labelManage/labelManage",
                        "createTime": "2020-11-18T14:37:29",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 791,
                        "menuType": "M",
                        "menuSort": 4
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuIconStr": "",
                        "menuPid": 787,
                        "menuName": "全屋智能产品库",
                        "updateTime": "2022-11-01T09:51:19",
                        "menuRemark": "",
                        "menuModal": "/wholeHouseSmart",
                        "createTime": "2021-05-13T09:23:51",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1300,
                                "menuName": "智能产品管理",
                                "updateTime": "2021-05-13T09:25:33",
                                "menuRemark": "",
                                "menuModal": "/productManage/wholeHouseSmart",
                                "createTime": "2021-05-13T09:25:33",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1301,
                                "menuType": "C",
                                "menuSort": 0
                            },
                            {
                                "menuPerms": "productManage:wholeHouseSmart:brandManage",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1300,
                                "menuName": "智能品牌管理",
                                "updateTime": "2023-11-07T19:15:56",
                                "menuRemark": "",
                                "menuModal": "/productManage/wholeHouseSmart/brandManage",
                                "createTime": "2021-05-13T09:27:08",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1302,
                                "menuType": "C",
                                "menuSort": 2
                            },
                            {
                                "menuPerms": "productManage:wholeHouseSmart:categoryManage",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1300,
                                "menuName": "智能产品分类管理",
                                "updateTime": "2023-11-07T19:17:50",
                                "menuRemark": "",
                                "menuModal": "/productManage/wholeHouseSmart/categoryManage",
                                "createTime": "2021-05-13T09:28:09",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1303,
                                "menuType": "C",
                                "menuSort": 3
                            },
                            {
                                "menuPerms": "productManage:wholeHouseSmart:planData",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1300,
                                "menuName": "全屋智能方案",
                                "updateTime": "2023-11-07T19:19:32",
                                "menuRemark": "",
                                "menuModal": "/productManage/wholeHouseSmart/planData",
                                "createTime": "2021-06-03T16:38:19",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1379,
                                "menuType": "C",
                                "menuSort": 4
                            }
                        ],
                        "menuId": 1300,
                        "menuType": "M",
                        "menuSort": 5
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 787,
                        "menuName": "全屋WiFi配置",
                        "updateTime": "2022-11-01T09:41:19",
                        "menuRemark": "",
                        "menuModal": "/wifiConfiguration",
                        "createTime": "2021-09-23T14:12:36",
                        "menuUrlType": 1,
                        "childMenus": [
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1457,
                                "menuName": "全屋WiFi套餐",
                                "updateTime": "2021-09-23T14:13:07",
                                "menuRemark": "",
                                "menuModal": "/wifiConfiguration/wifiPackage",
                                "createTime": "2021-09-23T14:13:07",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1458,
                                "menuType": "M",
                                "menuSort": 1
                            },
                            {
                                "menuPerms": "",
                                "menuStatus": 0,
                                "menuVisible": 0,
                                "menuPid": 1457,
                                "menuName": "全屋WiFi设备",
                                "updateTime": "2021-09-23T14:13:34",
                                "menuRemark": "",
                                "menuModal": "/wifiConfiguration/wifiDevices",
                                "createTime": "2021-09-23T14:13:34",
                                "menuUrlType": 1,
                                "childMenus": [],
                                "menuId": 1469,
                                "menuType": "M",
                                "menuSort": 2
                            }
                        ],
                        "menuId": 1457,
                        "menuType": "M",
                        "menuSort": 37
                    }
                ],
                "menuId": 787,
                "menuType": "M",
                "menuSort": 4
            },
            {
                "menuPerms": "",
                "menuStatus": 0,
                "menuVisible": 0,
                "menuIconStr": "shop",
                "menuPid": 0,
                "menuName": "商城设置",
                "updateTime": "2024-08-31T10:27:02",
                "menuRemark": "",
                "menuModal": "/shop",
                "createTime": "2020-11-18T14:13:58",
                "menuUrlType": 1,
                "childMenus": [
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 780,
                        "menuName": "商户认证",
                        "updateTime": "2020-11-18T14:16:04",
                        "menuRemark": "",
                        "menuModal": "shopManage/shopApprove",
                        "createTime": "2020-11-18T14:16:04",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 782,
                        "menuType": "C",
                        "menuSort": 2
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 780,
                        "menuName": "我的店铺",
                        "updateTime": "2020-11-18T14:17:05",
                        "menuRemark": "",
                        "menuModal": "/storeManage/commodityManage",
                        "createTime": "2020-11-18T14:17:05",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 783,
                        "menuType": "M",
                        "menuSort": 3
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 780,
                        "menuName": "我的门店",
                        "updateTime": "2020-11-18T14:17:05",
                        "menuRemark": "",
                        "menuModal": "/storeManage/commodityManage",
                        "createTime": "2020-11-18T14:17:05",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 7844,
                        "menuType": "M",
                        "menuSort": 6
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 78012,
                        "menuName": "我的员工",
                        "updateTime": "2020-11-18T14:17:05",
                        "menuRemark": "",
                        "menuModal": "/storeManage/commodityManage",
                        "createTime": "2020-11-18T14:17:05",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 78233,
                        "menuType": "M",
                        "menuSort": 3
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 721380,
                        "menuName": "角色权限管理",
                        "updateTime": "2020-11-18T14:17:05",
                        "menuRemark": "",
                        "menuModal": "/storeManage/commodityManage",
                        "createTime": "2020-11-18T14:17:05",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 783,
                        "menuType": "M",
                        "menuSort": 3
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 1,
                        "menuPid": 780,
                        "menuName": "收款账户",
                        "updateTime": "2024-09-03T14:11:58",
                        "menuRemark": "",
                        "menuModal": "/storeManage/shopMange",
                        "createTime": "2020-11-18T14:15:17",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 781,
                        "menuType": "M",
                        "menuSort": 1
                    },

                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuPid": 780,
                        "menuName": "支付签约",
                        "updateTime": "2023-12-19T16:39:44",
                        "menuRemark": "",
                        "menuModal": "/storeManage/storeInfor/components/first",
                        "createTime": "2020-11-18T14:20:11",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 784,
                        "menuType": "M",
                        "menuSort": 4
                    },
                    {
                        "menuPerms": "",
                        "menuStatus": 0,
                        "menuVisible": 0,
                        "menuIconStr": "",
                        "menuPid": 780,
                        "menuName": "账单明细",
                        "updateTime": "2023-11-08T10:05:36",
                        "menuRemark": "",
                        "menuModal": "/storeManage/storeAccount",
                        "createTime": "2020-11-18T14:24:45",
                        "menuUrlType": 1,
                        "childMenus": [],
                        "menuId": 786,
                        "menuType": "M",
                        "menuSort": 4
                    }
                ],
                "menuId": 780,
                "menuType": "M",
                "menuSort": 7
            }




        ],
            "flag": 1,
                "resetDate": "2023-06-28",
                    "shopOwner": "0",
                        "source": "system",
                            "roleList": [
                                {
                                    "roleId": 1,
                                    "roleName": "超级管理员",
                                    "roleType": 1
                                }
                            ],
                                "userName": "超管",
                                    "userId": 1,
                                        "pWErrorNum": 0,
                                            "freeze": 0,
                                                "size": 5000,
                                                    "orgCode": "0000000000000",
                                                        "permissions": [
                                                            "product:manage:item:update",
                                                            "product:manage:item:updateStatus",
                                                            "product:manage:item:delete",
                                                            "promotion:member:getMemberDetailList",
                                                            "product:manage:item:copyH5Link",
                                                            "product:manage:product:getProductById",
                                                            "promotion:manage:shopAttention:shopAttentionPage",
                                                            "product:manage:item:updateStatus",
                                                            "product:manage:product:deleteTopInfoByDate",
                                                            "product:manage:product:importTopInfoExcel",
                                                            "product:zdgsFivegTerminalSummary:delete",
                                                            "product:zdgsFivegTerminalSummary:importFivegTerminalSummary",
                                                            "product:supplyOrder:delete",
                                                            "product:supplyOrder:importSupplyOrder",
                                                            "product:manage:terminalStockData:importTerminalStock",
                                                            "product:manage:channelData:importChannelData",
                                                            "product:manage:channelData:deleteChannelDatas",
                                                            "product:manage:salesTarget:addSalesTargetData",
                                                            "product:manage:salesTarget:deleteSalesTargetDatas",
                                                            "product:manage:salesTarget:updateSalesTargetData",
                                                            "product:manage:salesAnalysisReport:importSalesAnalysisReport",
                                                            "product:manage:salesAnalysisReport:truncateSalesAnalysisReport",
                                                            "product:manage:item:update",
                                                            "product:manage:zdgsTerminalTask:add",
                                                            "product:manage:zdgsTerminalTask:update",
                                                            "product:manage:zdgsTerminalTask:delete",
                                                            "product:manage:zdgsProduct:importData",
                                                            "product:manage:zdgsSaleIemi:importData",
                                                            "promotion:manage:shopAttention:export",
                                                            "product:manage:zdgsSaleIemi:deleteById",
                                                            "product:manage:itemCategory:getMaintainSku",
                                                            "order:manage:countOrder:export",
                                                            "product:manage:product:downLoadExcel",
                                                            "order:manage:cardBroadband:addCbb",
                                                            "order:manage:cardBroadband:updateCbbById",
                                                            "order:manage:cardBroadband:delCbb",
                                                            "product:manage:zdgsTerminalTask:add",
                                                            "product:manage:product:downLoadExcel",
                                                            "product:manage:product:downLoadExcel",
                                                            "order:manage:xcxPackage:add",
                                                            "order:manage:xcxPackage:update",
                                                            "order:manage:xcxPackage:delete",
                                                            "order:manage:network:exportNetworkByData",
                                                            "product:manage:product:downLoadExcel",
                                                            "product:manage:product:downLoadExcel",
                                                            "promotion:knowledge:base:addKnowledge",
                                                            "promotion:knowledge:base:updateKnowledge",
                                                            "promotion:knowledge:base:deleteKnowledge",
                                                            "promotion:knowledge:base:auditList",
                                                            "promotion:knowledge:base:carousel",
                                                            "promotion:knowledge:base:selectKnowledge",
                                                            "promotion:knowledge:base:category:add",
                                                            "promotion:knowledge:base:category:update",
                                                            "promotion:knowledge:base:category:deleteCategory",
                                                            "product:manage:product:downLoadExcel",
                                                            "product:manage:product:downLoadExcel",
                                                            "product:manage:plan:addPlan'",
                                                            "product:manage:plan:updatePlan",
                                                            "product:manage:plan:deletePlan",
                                                            "product:manage:plan:hotPlan",
                                                            "product:manage:plan:zhuPlan",
                                                            "product:manage:planShop:addPlanShop",
                                                            "product:manage:qwznGoods:addGoods",
                                                            "product:manage:qwznGoods:update",
                                                            "product:manage:qwznGoods:deleteById",
                                                            "product:manage:qwznGoods:changeSaleStatus",
                                                            "product:manage:qwznGoods:getList",
                                                            "product:manage:itemCategory:getMaintainSku",
                                                            "promotion:manage:hdShophd:delete",
                                                            "product:manage:item:delete",
                                                            "promotion:coupon:saveOrUpdateCoupon",
                                                            "promotion:coupon:deleteCouponById",
                                                            "promotion:coupon:getCouponDetailPageList",
                                                            "promotion:coupon:topCoupon",
                                                            "user:manage:KhDesign:save",
                                                            "user:manage:KhDesign:download",
                                                            "user:manage:KhDesign:delete",
                                                            "user:manage:KhDesign:audit",
                                                            "promotion:manage:specialType:add",
                                                            "promotion:manage:specialType:update",
                                                            "promotion:manage:specialType:delete",
                                                            "promotion:manage:specialType:insert",
                                                            "promotion:manage:specialDetail:add",
                                                            "promotion:manage:specialDetail:update",
                                                            "promotion:manage:specialDetail:delete",
                                                            "order:capWithdrawal:subMchWithdraw",
                                                            "order:capWithdrawal:subMchWithdraw",
                                                            "order:capWithdrawal:updateBankInfo",
                                                            "order:capWithdrawal:export",
                                                            "order:capWithdrawal:getCapPayWithdrawalList",
                                                            "",
                                                            "",
                                                            "bannerAudit:pic:upload",
                                                            "banner:pic:upload",
                                                            "exGoods:pic:upload",
                                                            "knowBase:pic:upload",
                                                            "knowType:pic:upload",
                                                            "knowAudit:pic:upload",
                                                            "label:pic:upload",
                                                            "prize:pic:upload",
                                                            "brand:pic:upload",
                                                            "type:pic:upload",
                                                            "product:pic:upload",
                                                            "wifi:pic:upload",
                                                            "comManage:pic:upload",
                                                            "goodsList:pic:upload",
                                                            "chainGoods:pic:upload",
                                                            "chainlist:pic:upload",
                                                            "per:pic:upload",
                                                            "sign:pic:upload",
                                                            "thematic:pic:upload",
                                                            "thematicDetail:pic:upload",
                                                            "wifiPack:pic:upload",
                                                            "product:pic:upload",
                                                            "product:pic:upload",
                                                            "awardmanage:point:getMemberDetailList",
                                                            "awardmanage:point:update",
                                                            "awardmanage:point:delete",
                                                            "promotion:manage:integralDetail:queyListPointDetailSocial",
                                                            "promotion:manage:integralDetail:getSelectPage",
                                                            "user:manage:dic:saveOrUpdateSdKind",
                                                            "user:manage:account:saveOrUpdateAccount",
                                                            "product:shop:exportShopsInfo",
                                                            "user:manage:origination:add",
                                                            "promotion:manage:integralDetail:updateIntegral",
                                                            "user:manage:role:addRole",
                                                            "promotion:manage:profitshare:saveProfitshare",
                                                            "product:manage:product:downLoadExcel",
                                                            "order:capWithdrawal:getErrorFile",
                                                            "product:shop:shopReviewById",
                                                            "order:manage:profitShare:doProfitSharingFinish",
                                                            "product:shop:updateShopStatus",
                                                            "user:manage:menu:saveOrUpdateSysMenu",
                                                            "product:shop:updateShopPayment",
                                                            "promotion:manage:memberGrade:addGrade",
                                                            "order:manage:xcxUserOrder:export",
                                                            "product:manage:product:saveProduct",
                                                            "product:manage:item:exportSkuListByShopId",
                                                            "product:manage:product:auditProduct",
                                                            "product:manage:saveOrUpdateBrand",
                                                            "promotion:manage:hdShophd:audit",
                                                            "product:manage:specification:add",
                                                            "product:manage:itemCategory:add",
                                                            "product:manage:item:exportChainSkuListByOrgCode",
                                                            "promotion:manage:hdShophd:saveOrUpdate",
                                                            "product:manage:label:add",
                                                            "promotion:xcx:insertDrawAwards",
                                                            "product:manage:phoneNumber:add",
                                                            "order:manage:xcxDrawRecord:auditDrawRecord",
                                                            "order:manage:kdytExchangeGoods:addGoodInfo",
                                                            "product:manage:phoneGrade:update",
                                                            "order:manage:kdytExchangeRecord:updateRecordAddressById",
                                                            "product:manage:platform:importPlatformData",
                                                            "product:zdgsFivegTerminalData:importFivegTerminal",
                                                            "user:manage:sysConfigType:saveOrUpdateSysType",
                                                            "user:manage:infor:delete",
                                                            "user:manage:operLog:delete",
                                                            "user:manage:job:saveOrUpdateSysJob",
                                                            "user:manage:account:saveOrUpdateAccount",
                                                            "user:manage:KhDesign:audit",
                                                            "user:manage:KhDesign:download",
                                                            "product:category:saveOrUpdateCategory",
                                                            "user:manage:account:saveOrUpdateAccount",
                                                            "product:manage:qwznBrand:saveOrUpdateBrand",
                                                            "product:manage:qwznCategory:saveOrUpdateCategory",
                                                            "promotion:manage:pointGrade:getPointGradePage",
                                                            "promotion:manage:pointsAccumulate:getPointsAccumulatePage",
                                                            "promotion:member:getMemberDetailList",
                                                            "member:app:manageArticle:listSysArtaclePage",
                                                            "memberManage:userDetail",
                                                            "member:userTag:getUserTagInfoPage",
                                                            "member:userTag:getTagPage",
                                                            "member:userTag:getTagAttributePage",
                                                            "user:manage:account:saveOrUpdateAccount",
                                                            "user:manage:dic:saveOrUpdateSdKind",
                                                            "product:manage:label:getLabelList",
                                                            "user:manage:origination:update",
                                                            "user:manage:role:updateRole",
                                                            "promotion:manage:profitshare:deleteProfitshare",
                                                            "product:manage:latitudeLongitude:getFillLatitudeLongitude",
                                                            "product:shop:auditingDelete",
                                                            "order:manage:profitShare:doProfitSharingFinishAll",
                                                            "user:manage:openTheShop",
                                                            "promotion:member:deleteXcxUserDetail",
                                                            "user:manage:menu:saveOrUpdateSysMenu",
                                                            "order:manage:judgeOrderHasOrangeStaging",
                                                            "promotion:manage:memberGrade:deleteGrade",
                                                            "order:manage:xcxUserOrder:updateStatus",
                                                            "product:manage:product:deleteProduct",
                                                            "product:manage:deleteBrand",
                                                            "product:manage:specification:update",
                                                            "product:manage:itemCategory:update",
                                                            "product:manage:label:updateLabelInfo",
                                                            "promotion:xcx:updateDrawAwards",
                                                            "product:manage:phoneNumber:delete",
                                                            "order:manage:xcxDrawRecord:editReceiveAddress",
                                                            "order:manage:kdytExchangeGoods:updateGoodByGoodId",
                                                            "product:manage:phoneGrade:export:listPhoneGrade",
                                                            "order:manage:kdytExchangeRecord:updateRecordStatusById",
                                                            "product:manage:product:downLoadExcel",
                                                            "product:manage:product:downLoadExcel",
                                                            "user:manage:sysConfigType:saveOrUpdateSysType",
                                                            "user:manage:job:reStartAllJobs",
                                                            "user:manage:account:saveOrUpdateAccount",
                                                            "product:category:saveOrUpdateCategory",
                                                            "user:manage:account:saveOrUpdateAccount",
                                                            "product:manage:qwznBrand:saveOrUpdateBrand",
                                                            "product:manage:qwznBrand:saveOrUpdateBrand",
                                                            "promotion:manage:pointGrade:addPointGrade",
                                                            "promotion:manage:pointsAccumulate:addPoints",
                                                            "promotion:member:updateXcxUserDetail",
                                                            "member:userTag:saveOrUpdateTag",
                                                            "member:userTag:saveOrUpdateTagAttribute",
                                                            "user:manage:account:deleteAccount",
                                                            "user:manage:dic:deleteSdKind",
                                                            "user:manage:origination:delete",
                                                            "product:manage:product:listProduct",
                                                            "user:manage:role:deleteRole",
                                                            "user:manage:infor:downloadArchiveLog",
                                                            "order:manage:profitShare:doProfitSharingFinishByShop",
                                                            "product:shop:downloadOrgXcxQrCode",
                                                            "promotion:manage:integralDetail:findIntegral",
                                                            "user:manage:menu:deleteSysMenuById",
                                                            "order:manage:doOrderRefund",
                                                            "product:manage:specification:delete",
                                                            "product:manage:itemCategory:delete",
                                                            "promotion:manage:hdShophd:getAuditLogs",
                                                            "product:manage:label:delete",
                                                            "promotion:xcx:delDrawAwards",
                                                            "product:manage:phoneNumber:export:listPhoneNumber",
                                                            "order:manage:kdytExchangeGoods:changeGoodByGoodId",
                                                            "product:zdgsFivegTerminalData:delete",
                                                            "user:manage:sysConfigType:deleteSysType",
                                                            "user:manage:job:saveOrUpdateSysJob",
                                                            "user:manage:account:deleteAccount",
                                                            "product:category:deleteCategoryById",
                                                            "user:manage:account:deleteAccount",
                                                            "product:manage:qwznBrand:deleteBrandById",
                                                            "product:manage:qwznCategory:deleteCategory",
                                                            "promotion:manage:pointGrade:delPointGrade",
                                                            "promotion:manage:pointsAccumulate:addPoints",
                                                            "promotion:member:deleteXcxUserDetail",
                                                            "promotion:article:manageArtacle:saveActicle",
                                                            "member:app:manageArticle:deleteArtacle",
                                                            "member:userTag:delTagById",
                                                            "member:userTag:delTagAttributeById",
                                                            "user:manage:account:replaceAccountPassword",
                                                            "user:manage:role:updateRole",
                                                            "product:shop:superUpdateShop",
                                                            "product:shop:showShopQrCode",
                                                            "promotion:manage:xcxUserSource:page",
                                                            "order:manage:cancelOrder",
                                                            "product:manage:specificationOption:page",
                                                            "product:manage:itemCategory:updateStatus",
                                                            "product:manage:phoneNumber:import",
                                                            "user:manage:job:openOrCloseSysJob",
                                                            "user:manage:account:replaceAccountPassword",
                                                            "product:shop:auditWxQrCode",
                                                            "promotion:manage:pointsAccumulate:getPointsAccumulateDetail",
                                                            "promotion:member:getPointInfo",
                                                            "member:userTag:getTagRulePage",
                                                            "member:userTag:getTagList",
                                                            "member:app:manageArticle:findArtacleDetail",
                                                            "product:shop:updateShopPayment",
                                                            "product:shop:choosePayMethod",
                                                            "order:manage:export:ExportOrder",
                                                            "product:manage:itemCategory:update:template",
                                                            "user:manage:job:openOrCloseSysJob",
                                                            "user:manage:account:isFreezeAccount",
                                                            "user:manage:account:isFreezeAccount",
                                                            "promotion:member:getPointDetailPage",
                                                            "promotion:manage:pointGrade:getMaxPointGrade",
                                                            "promotion:manage:memberGrade:listGrade2",
                                                            "member:userTag:saveOrUpdateTagRule",
                                                            "zos:file:put",
                                                            "product:shop:getShopStaffInfo",
                                                            "order:manage:addOrderNote",
                                                            "user:manage:job:deleteSysJob",
                                                            "user:manage:account:isFreezeAccount",
                                                            "user:manage:account:isFreezeAccount",
                                                            "promotion:manage:xcxUserSource:page",
                                                            "promotion:member:getUserCardDetail",
                                                            "member:userTag:delTagRuleById",
                                                            "member:app:manageArticle:updateArticle",
                                                            "product:shop:updateShopStatus",
                                                            "order:manage:refundOrder",
                                                            "promotion:manage:pointGrade:getPointGradeList",
                                                            "product:shop:restartPaymentInfo",
                                                            "order:manage:updateStatusById",
                                                            "order:capWithdrawal:getFundInfoByShopId",
                                                            "order:manage:xcxDanc:iccid",
                                                            "product:shop:cloudFlashPayShopPayment"
                                                        ],
                                                            "userAccount": "yhjadmin",
                                                                "messagestock": false
}





